In [ ]:
import pandas as pd

In [ ]:
movie=pd.read_csv("/content/Netflix_Dataset_Movie.csv")
movie.head()

   Movie_ID  Year                          Name
0         1  2003               Dinosaur Planet
1         2  2004    Isle of Man TT 2004 Review
2         3  1997                     Character
3         4  1994  Paula Abdul's Get Up & Dance
4         5  2004      The Rise and Fall of ECW

In [ ]:
ratings=pd.read_csv("/content/Netflix_Dataset_Rating.csv.zmdownload")
ratings.head()

   User_ID  Rating  Movie_ID
0   712664       5         3
1  1331154       4         3
2  2632461       3         3
3    44937       5         3
4   656399       4         3

In [ ]:
movie_ratings=pd.merge(movie,ratings)
movie_ratings.head()

   Movie_ID  Year       Name  User_ID  Rating
0         3  1997  Character   712664       5
1         3  1997  Character  1331154       4
2         3  1997  Character  2632461       3
3         3  1997  Character    44937       5
4         3  1997  Character   656399       4

In [ ]:
movie_ratings=movie_ratings.pivot_table(index="User_ID",columns="Name",values="Rating")
movie_ratings.head()

Name,10,10 Things I Hate About You,11:14,13 Ghosts,18 Again,1984,2 Fast 2 Furious,200 Cigarettes,2010: The Year We Make Contact,24 Hour Party People,...,X2: X-Men United,Xena: Warrior Princess: Season 3,Xena: Warrior Princess: Series Finale,Y Tu Mama Tambien,Yi Yi,Yojimbo,Young Black Stallion,Youngblood,Yu-Gi-Oh!: The Movie,Zorro
User_ID,,,,,,,,,,,,,,,,,,,,,
6,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,NaN,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,...,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
movie['Name'][movie['Name'].str.contains('Wild')]

139                                       Lost in the Wild
219                Winston Churchill: The Wilderness Years
329                                            Wild Things
841                                     Reap the Wild Wind
1508                         National Lampoon's Van Wilder
                               ...
17374    Ocean Wilds: Realm of the Killer Whales/Sperm ...
17390                                   Wildboyz: Season 1
17482    Crocodile Hunter: Wildest Home Videos / Big Cr...
17614                                  Scarecrow Gone Wild
17765    Where the Wild Things Are and Other Maurice Se...
Name: Name, Length: 76, dtype: object

In [ ]:
wild_rating=movie_ratings['Wild Things']
wild_rating.head()

User_ID
6      NaN
7      NaN
79     NaN
97     NaN
134    5.0
Name: Wild Things, dtype: float64

In [ ]:
similar_movies=movie_ratings.corrwith(wild_rating)
similar_movies.head()

Name
10                            0.295846
10 Things I Hate About You    0.238126
11:14                         0.265127
13 Ghosts                     0.263920
18 Again                      0.247475
dtype: float64

In [ ]:
similar_movies=similar_movies.sort_values(ascending=False)
similar_movies.head()s

Name
Wild Things     1.000000
Poison Ivy 2    0.441186
Players Club    0.417944
Jade            0.382871
Species II      0.377791
dtype: float64